#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]
  then
    echo "Invalid arguments: ./create_project.sh PROJECT_NAME ORGANIZATION_ID SERVICE_ID SERVICE_PORT"
    exit 1
fi

PROJECT_NAME=$1
ORGANIZATION_ID=$2
SERVICE_ID=$3
SERVICE_PORT=$4

TEMPLATE_DIR=template
SRC_DIR=/opt/singnet/$PROJECT_NAME
PROTO_DIR=$SRC_DIR/service_spec
PROTO_FILE=$PROTO_DIR/$PROJECT_NAME.proto
PROTO_SED_DIR_START=$(echo service_spec | sed 's_/_\\/_g')
SERVER_PY_FILE=$SRC_DIR/server.py
CLIENT_PY_FILE=$SRC_DIR/client.py
BUILD_SCRIPT_FILE=$SRC_DIR/build.sh

DAEMON_CONFIG_DIRNAME=config
DAEMON_CONFIG_FILENAME=snetd.config.json
DAEMON_CONFIG_DIR=$SRC_DIR/$DAEMON_CONFIG_DIRNAME
DAEMON_CONFIG_FILE=$DAEMON_CONFIG_DIR/$DAEMON_CONFIG_FILENAME
START_SERVICE_SCRIPT_FILE=$SRC_DIR/publishAndStartService.sh
CLIENT_OPEN_CHANNEL_SCRIPT_FILENAME=openChannel.sh
CLIENT_OPEN_CHANNEL_SCRIPT_FILE=$SRC_DIR/$CLIENT_OPEN_CHANNEL_SCRIPT_FILENAME
CLIENT_TEST_SCRIPT_FILENAME=testServiceRequest.sh
CLIENT_TEST_SCRIPT_FILE=$SRC_DIR/$CLIENT_TEST_SCRIPT_FILENAME

TEMPLATE_PROTO=$TEMPLATE_DIR/proto.template.proto
TEMPLATE_BUILD_SCRIPT=$TEMPLATE_DIR/build.template.sh
TEMPLATE_SERVER=$TEMPLATE_DIR/server.template.py
TEMPLATE_CLIENT=$TEMPLATE_DIR/client.template.py
TEMPLATE_DAEMON_CONFIG_FILE=$TEMPLATE_DIR/daemonConfigFile.template.json
TEMPLATE_START_SERVICE_SCRIPT=$TEMPLATE_DIR/publishAndStartService.template.sh
TEMPLATE_OPEN_CHANNEL_SCRIPT=$TEMPLATE_DIR/openChannel.template.sh
TEMPLATE_CLIENT_TEST_SCRIPT=$TEMPLATE_DIR/testService.template.sh

PROJECT_TAG=__PROJECT__
SERVICE_PORT_TAG=__SERVICE_PORT__
SERVICE_ID_TAG=__SERVICE_ID__
ORGANIZATION_ID_TAG=__ORGANIZATION_ID__
PROTO_DIR_TAG=__PROTO_DIR__
DAEMON_CONFIG_FILE_TAG=__DAEMON_CONFIG_FILE__

PYTHON_PB2=__PYTHON_PB2__
PYTHON_PB2_GRPC=__PYTHON_PB2_GRPC__

if [ -d "$SRC_DIR" ] || [ -f $SRC_DIR ]; then
    echo "ERROR: $SRC_DIR already exists"
    exit 1
fi

mkdir -p $PROTO_DIR
mkdir -p $SRC_DIR
mkdir -p $DAEMON_CONFIG_DIR

cat $TEMPLATE_PROTO | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" > $PROTO_FILE
cat $TEMPLATE_BUILD_SCRIPT > $BUILD_SCRIPT_FILE
cat $TEMPLATE_SERVER | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" | sed "s/$SERVICE_PORT_TAG/$SERVICE_PORT/g" | sed "s/$PYTHON_PB2/${PROJECT_NAME}_pb2/g" | sed "s/$PYTHON_PB2_GRPC/${PROJECT_NAME}_pb2_grpc/g" > $SERVER_PY_FILE
cat $TEMPLATE_CLIENT | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" | sed "s/$SERVICE_PORT_TAG/$SERVICE_PORT/g" | sed "s/$PYTHON_PB2/${PROJECT_NAME}_pb2/g" | sed "s/$PYTHON_PB2_GRPC/${PROJECT_NAME}_pb2_grpc/g" > $CLIENT_PY_FILE
cat $TEMPLATE_DAEMON_CONFIG_FILE | sed "s/$ORGANIZATION_ID_TAG/$ORGANIZATION_ID/g" | sed "s/$SERVICE_ID_TAG/$SERVICE_ID/g" | sed "s/$SERVICE_PORT_TAG/$SERVICE_PORT/g" > $DAEMON_CONFIG_FILE
cat $TEMPLATE_OPEN_CHANNEL_SCRIPT | sed "s/$ORGANIZATION_ID_TAG/$ORGANIZATION_ID/g" | sed "s/$SERVICE_ID_TAG/$SERVICE_ID/g" > $CLIENT_OPEN_CHANNEL_SCRIPT_FILE
cat $TEMPLATE_START_SERVICE_SCRIPT | sed "s/$ORGANIZATION_ID_TAG/$ORGANIZATION_ID/g" | sed "s/$SERVICE_ID_TAG/$SERVICE_ID/g" | sed "s/$PROTO_DIR_TAG/$PROTO_SED_DIR_START/g" | sed "s/$DAEMON_CONFIG_FILE_TAG/$DAEMON_CONFIG_DIRNAME\/$DAEMON_CONFIG_FILENAME/g" > $START_SERVICE_SCRIPT_FILE
cat $TEMPLATE_CLIENT_TEST_SCRIPT | sed "s/$ORGANIZATION_ID_TAG/$ORGANIZATION_ID/g" | sed "s/$SERVICE_ID_TAG/$SERVICE_ID/g" > $CLIENT_TEST_SCRIPT_FILE

chmod 755 $START_SERVICE_SCRIPT_FILE
chmod 755 $CLIENT_OPEN_CHANNEL_SCRIPT_FILE
chmod 755 $CLIENT_TEST_SCRIPT_FILE
chmod 755 $BUILD_SCRIPT_FILE
